### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-html-boilerplate-linting-and-code-style-uRxwab#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://harr1193.github.io/MI-449-SS17-741-html-boilerplate-linting-and-code-style-uRxwab/) and meets the following criteria:

- [x] The files from your last project are copied and pasted into the directory for this project
- [x] Your code returns no errors (warnings are OK) when pasted into the [W3C Validator](https://validator.w3.org/#validate_by_input) (this will also be expected for all future projects)
- [x] Consistent spacing and indentation are used on every line (this will also be expected for all future projects)
- [x] `skeleton.css` is used to improve the design of the page

**Comment by KatieMFritz** [comment]
Hi Kyle, don't hate me. 😬 

There are some things that were wrong with your last project that are still wrong in this one - probably we didn't get back to you before you copied/pasted. I'm sorry about that inconvenience! Hopefully this won't be a problem most of the time, since most projects you start from scratch instead of copying previous code.

Can you get the last project approved first, then update this project based on that approved code?

Other than that, your spacing and indentation look almost perfect - **check out line 9 and line 20/21 of your current index.html.** The code is technically valid, and skeleton.css is working. It's almost there! 👍

**Comment by harr1193** [comment]
Made the changes from the first project and hosted it.

**Comment by KatieMFritz** [comment]
Super close. ⭐️ 

This bit (lines 19-20) is still a little wonky with the indentation:

```
    <a href="http://www.solarguard.com/spcrew11a.jpg">
    <img src="http://www.solarguard.com/spcrew11a.jpg" alt="SpacePatrol"></a>
```
From the lesson:
> Nested elements are always indented exactly one level beyond the indentation of their parent

The `img` is nested inside the `a`, so it should be indented one level beyond the `a`. For consistency, the closing `</a>` should be on its own line, like the opening `<a>` is (and at the same indentation level as the opening `<a>`. It's just like how you indent `li` inside of `ul`.  Does that make sense?

Make that one last change, and you'll be ready for your next mission. 🚀

**Comment by harr1193** [comment]
Made the changes

**Comment by KatieMFritz** [comment]
Great!

I just realized the `head` of the document is missing the `<meta charset="utf-8">`.  In most cases, this won't cause a problem, but it can lead to weird things happening with your content in some situations. 

I'm not going to make you redo it, since I missed it before - but for future HTML projects, be sure to include the full boilerplate. You can read more about it on [page 1 of the lesson](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-boilerplate-linting-and-code-style/1).

:shipit: and celebrate!
